name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: 🚀 Features
    labels: ["feature", "enhancement"]
  - title: 🐛 Bug Fixes
    labels: ["bug", "fix"]
  - title: 🛠 Improvements
    labels: ["refactor", "improvement"]
  - title: 🧹 Maintenance
    labels: ["chore", "dependencies"]

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
change-title-escapes: '\<\>&'

template: |
  ## Changes in $NEXT_PATCH_VERSION

  $CHANGES

  ### Contributors
  $CONTRIBUTORS
