name: Update Documentation

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
      - "**/requirements.txt"
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pydoc-markdown diagrams

      - name: Update architecture diagram
        run: python .github/scripts/generate_architecture.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update architecture documentation"
          file_pattern: "ARCHITECTURE.md docs/**/*"
