name: hsqlparser
version: 0.1.0.0
github: "pyHMSSQL/hsqlparser"
license: BSD3
author: "pyHMSSQL Team"
maintainer: "example@example.com"
copyright: "2024 pyHMSSQL Team"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/pyHMSSQL/hsqlparser#readme>

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - aeson
  - text
  - containers
  - megaparsec
  - bytestring

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  hsqlparser:
    main: parser.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hsqlparser

tests:
  hsqlparser-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hsqlparser
