apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hyperkv
  labels:
    app: hyperkv
spec:
  serviceName: hyperkv-headless
  replicas: 3
  selector:
    matchLabels:
      app: hyperkv
  template:
    metadata:
      labels:
        app: hyperkv
    spec:
      serviceAccountName: hyperkv
      securityContext:
        fsGroup: 1000
      containers:
        - name: hyperkv
          image: hyperkv:latest
          imagePullPolicy: Always
          ports:
            - name: kvstore
              containerPort: 6379
              protocol: TCP
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: raft
              containerPort: 7000
              protocol: TCP
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AUTH_PASSWORD
              valueFrom:
                secretRef:
                  name: hyperkv-secret
                  key: auth-password
            - name: PYTHONPATH
              value: "/app"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/hyperkv
            - name: scripts
              mountPath: /scripts
            - name: logs
              mountPath: /var/log/hyperkv
          command: ["/bin/bash", "/scripts/entrypoint.sh"]
          livenessProbe:
            exec:
              command: ["/bin/bash", "/scripts/health-check.sh"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: hyperkv-config
        - name: scripts
          configMap:
            name: hyperkv-scripts
            defaultMode: 0755
        - name: logs
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "fast-ssd"
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: hyperkv-headless
  labels:
    app: hyperkv
spec:
  clusterIP: None
  ports:
    - name: kvstore
      port: 6379
      targetPort: 6379
    - name: raft
      port: 7000
      targetPort: 7000
  selector:
    app: hyperkv
---
apiVersion: v1
kind: Service
metadata:
  name: hyperkv-service
  labels:
    app: hyperkv
spec:
  type: ClusterIP
  ports:
    - name: kvstore
      port: 6379
      targetPort: 6379
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: hyperkv
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hyperkv
  labels:
    app: hyperkv
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperkv
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hyperkv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hyperkv
subjects:
  - kind: ServiceAccount
    name: hyperkv
    namespace: default
