apiVersion: v1
kind: Secret
metadata:
  name: hyperkv-secret
  labels:
    app: hyperkv
type: Opaque
data:
  # Base64 encoded password: "hyperkv-secret-password"
  auth-password: aHlwZXJrdi1zZWNyZXQtcGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: hyperkv-tls
  labels:
    app: hyperkv
type: kubernetes.io/tls
data:
  # These would be your actual TLS certificates in base64
  tls.crt: LS0tLS1CRUdJTi... # Your certificate
  tls.key: LS0tLS1CRUdJTi... # Your private key
