name: Count Lines of Code

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  count-loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Count lines of code
        uses: tj-actions/cloc@v1.3.3
        
      - name: Get the cloc badge
        uses: pxgamer/cloc-badge-action@v1.0.0
        id: cloc
        with:
          output_path: ./cloc.svg
          
      # Optional: Upload the badge as an artifact
      - name: Upload badge
        uses: actions/upload-artifact@v3
        with:
          name: cloc-badge
          path: ./cloc.svg