name: Generate LOC Badge

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cloc
        run: sudo apt-get update && sudo apt-get install -y cloc

      - name: Run cloc and save JSON
        run: cloc . --json --out=cloc-output.json

      - name: Extract total LOC and create badge JSON
        run: |
          total_lines=$(jq '.SUM.code' cloc-output.json)
          echo "{\"schemaVersion\":1,\"label\":\"Lines of Code\",\"message\":\"$total_lines\",\"color\":\"blue\"}" > loc-badge.json

      - name: Push badge to loc-badge branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch origin loc-badge || git checkout --orphan loc-badge
          git checkout loc-badge || git checkout -b loc-badge
          mv loc-badge.json ./loc-badge.json
          git add loc-badge.json
          git commit -m "Update LOC badge" || echo "No changes to commit"
          git push origin loc-badge
