name: Code Quality Analysis

on:
  push:
    branches: [main, develop]
    paths:
      - "**.py"
  pull_request:
    branches: [main, develop]
    paths:
      - "**.py"

jobs:
  pylint:
    name: Pylint Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black isort mypy
          pip install -r requirements.txt

      - name: Run Black formatter check
        run: |
          black --check --diff server/ tests/

      - name: Run isort import sorting check
        run: |
          isort --check-only --diff server/ tests/

      - name: Run pylint analysis
        run: |
          pylint server/ tests/ \
            --disable=C0114,C0115,C0116,R0903,R0913,R0914,W0613 \
            --max-line-length=100 \
            --output-format=colorized \
            --reports=no

      - name: Run mypy type checking
        run: |
          mypy server/ --ignore-missing-imports --check-untyped-defs
        continue-on-error: true
